language: android
jdk:
  - oraclejdk8

android:
  components:
  - tools
  - platform-tools
  - tools

  # The BuildTools version used by your project
  - build-tools-26.0.2
  - build-tools-27.0.3

  # The SDK version used to compile your project
  - android-26
  - android-27
  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
install: true
script: ./gradlew testWithCoverage -q
notifications:
  email: false

# cache between builds
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache