coverage:
  range: 70..100
  round: down
  precision: 2

  status:
    project: yes
    patch: yes
    changes: no

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  behavior: default
